### ISSUE TITLE
Style object to handle the looks of menu

### ISSUE THREAD

**Issue by ParadoxZero** [ParadoxZero/GameMenu-cpp#1]
It should include things like:

- Title color
- Title Font
- Item color
- Item font
- Size of title and items
- Relative Location (Choose from Left, right, centre)
- Background - Color or image.

**Comment by faraz16iqbal** [comment]
Is this issue still up for grabs?

**Comment by ParadoxZero** [comment]
Sure, I have not been maintaining this for a while now so you may face trouble to get this started. But you are definitely welcome to grab this issue. Let me know if you need any help.

**Comment by m5anksc0des** [comment]
hi! i wish to grab this project as one of first ones.Is  it still up for edits??

**Comment by ParadoxZero** [comment]
This has been implemented.
